baseURL = "http://example.org/"
languageCode = "en-us"
title = "Jeatsheets"

theme = "docdock"

[outputs]
home = [ "HTML", "RSS", "JSON"]


[[menu.shortcuts]]
pre = "<h3>More</h3>"
name = "<i class='fa fa-github'></i> My Github"
identifier = "ds"
url = "https://github.com/joalder"
weight = 1

[[menu.shortcuts]]
name = "<i class='fa fa-bookmark'></i> Hugo Docs"
identifier = "hugodoc"
url = "https://gohugo.io/"
weight = 2